/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    BpmnIcon: typeof import('./src/components/common/BpmnIcon.vue')['default']
    CollapseTitle: typeof import('./src/components/common/CollapseTitle.vue')['default']
    EditItem: typeof import('./src/components/common/EditItem.vue')['default']
    ElementBaseInfo: typeof import('./src/components/Panel/components/ElementBaseInfo.vue')['default']
    ElementCondition: typeof import('./src/components/Panel/components/ElementCondition.vue')['default']
    ElementDocument: typeof import('./src/components/Panel/components/ElementDocument.vue')['default']
    ElementExecutionListeners: typeof import('./src/components/Panel/components/ElementExecutionListeners.vue')['default']
    ElementStart: typeof import('./src/components/Panel/components/ElementStart.vue')['default']
    ElementUserTask: typeof import('./src/components/Panel/components/ElementUserTask.vue')['default']
    ElementUserTaskListener: typeof import('./src/components/Panel/components/ElementUserTaskListener.vue')['default']
    LucideIcon: typeof import('./src/components/common/LucideIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
